### PR TITLE
feat: avoid relative imports

### PR DESCRIPTION
**Pull request by AntonioVentilii-DFINITY**
We introduce the rule [no-relative-parent-imports](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-relative-parent-imports.md) that enforces the usage of absolute imports or aliases, but only if it refers to parent peers.

To completely avoid relative imports, we create a custom rule that simply check the import string.

### CODE REVIEW

**Comment by peterpeterparker** [comment]
Will it be easy to introduce in `oisy-wallet-signer`?

**Comment by AntonioVentilii-DFINITY** [comment]
I checked and not really... quite a lot of fixes. We can either disable for that one, or since it may be opinionated (maybe some projects prefer relative imports), we just don't add it, and I add it just in Oisy

**Comment by peterpeterparker** [comment]
It would be nice to have it as an option. Generally speaking it would be nice, as you already suggested, to allow consumer to opt-out certains rules if they wish. This way we can have this rule for example and use it in Oisy and, to get started, not in the library?

Alternatively, if `npm run lint --fix` fixes all issues, I'm not against running it on the signer and enforcing the rule. The signer lib is well covered by test.

**Review by peterpeterparker — APPROVED** [review]
LGTM, thx

**Pull request merged**
