### PR TITLE
feat: Add rules to enforce arrow functions

### PR DESCRIPTION
**Pull request by AntonioVentilii-DFINITY**
# Motivation

To further help with enforcing the arrow functions we add two rules and one plugin. This is one of the most suggested combination I found online:

- [prefer-arrow-callback](https://eslint.org/docs/latest/rules/prefer-arrow-callback): this will enforce arrow functions when given as callback to other statements;
- [func-style](https://eslint.org/docs/latest/rules/func-style): the default settings of this rule forces to avoid using declaration statements for functions, for example `function foo() {...}`
- [prefer-arrow](https://www.npmjs.com/package/eslint-plugin-prefer-arrow) plugin: with the configs set by us, the plugin will generally make notice of the usage of `function`.

# Changes

- Installed plugin [prefer-arrow](https://www.npmjs.com/package/eslint-plugin-prefer-arrow).
- Include rules in index file.
- Fix issues raised.

# Tests

The rules raised some new issues on this repo and we fixed them.

### CODE REVIEW

**Comment by AntonioVentilii-DFINITY** [comment]
@peterpeterparker note that the new plugin does not seem to be so well maintained ([last version 4 years ago](https://www.npmjs.com/package/eslint-plugin-prefer-arrow?activeTab=versions)). However there is not much to mantain except bumping dependencies.

There is an alternative with this other plugin that is a fork actually and seems more recent: https://www.npmjs.com/package/eslint-plugin-prefer-arrow-functions

What would you suggest?

**Comment by peterpeterparker** [comment]
Do we need the plugin? Maybe the rules already cover enough use cases at least to get started?

**Comment by AntonioVentilii-DFINITY** [comment]
I checked and it would have not raised any issues, without that plugin, in this repo. What I can do is to create a "simpler" rule like the one provided in the new plugin but limited to our usage

**Comment by peterpeterparker** [comment]
I see. Sounds cool to me if you think it makes sense? Your call.

**Comment by AntonioVentilii** [comment]
So, update here, @peterpeterparker :

I tried to create our own rule, trimming the one provided by those library. But it is basically an entire copy/paste minus 10/15 lines (over 350 lines total)...

So, I think it is ok to use the library we are currently using (it had more than 1 million download in the last week), and we can always replace it with our own code in the future, IF and WHEN the time arrives.

WDYT?

**Review by peterpeterparker — APPROVED** [review]
LGTM, thanks!

**Pull request closed without merging**
